accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
      login,
      logout,
      password_reset,
      password_reset_done,
      password_reset_confirm,
      password_reset_complete
      )

urlpatterns = [

    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name="login"),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name="logout"),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit/$', views.edit_profile, name="edit_profile"),
    url(r'^change-password/$', views.change_password, name="change_password"),

    url(r'^reset-password/$', password_reset, {
    'template_name': 'accounts/reset_password.html',
    'post_reset_redirect': 'accounts:password_reset_done',
    'email_template_name': 'accounts/reset_password_email.html'},
    name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'},
    name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
    {'template_name': 'accounts/reset_password_confirm.html',
    'post_reset_redirect': 'accounts:password_reset_complete'},
    name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,
    {'template_name': 'accounts/reset_password_complete.html'},
     name='password_reset_complete'),

]

home/urls.py
from django.conf.urls import url
from home.views import HomeView
from . import views

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^connect/(?P<operation>.+)(?P<pk>\d+)/$', views.change_friends, name='change_friends')
]

maxdjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from maxdjango import views
from maxdjango.views import login_redirect
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.login_redirect, name="login_redirect"),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
import os

class Post(models.Model):
    post = models.CharField(max_length=500)
    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name="owner", null=True)

    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user = current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.remove(new_friend)
        

# Create your models here.

home/forms.py
from django import forms
from home.models import Post

class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs = {
            'class': 'form-control',
            'placeholder': 'Write a post...'
        }
    ))

    class Meta():
        model = Post
        ## This will be read as a tuple object because of the ','
        fields = ('post', )

home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.generic import TemplateView
from home.forms import HomeForm
from django.shortcuts import render, redirect
from home.models import Post, Friend
from django.contrib.auth.models import User

class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get(self, request):
        form = HomeForm()
        posts = Post.objects.all().order_by('-created')
        ## users = User.objects.all() but inorder to remove the current username
        users = User.objects.exclude(id=request.user.id)
        friend = Friend.objects.get(current_user=request.user)
        friends = friend.users.all()

        args = {
            'form': form, 'posts': posts, 'users':users, 'friends': friends,
            }
        return render(request, self.template_name, args)



    def post(self, request):
        form = HomeForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            text = form.cleaned_data['post']
            ## to clean or remove the letters on the form after submitted
            form = HomeForm() ## This will remove it
            return redirect('home:home')
            ## to re-display the current page and and remove the text argument that will be posted

        args = {'form': form, 'text': text}
        return render(request, self.template_name, args)

def change_friends(request, operation, pk):
    new_friend = User.objects.get(pk=pk)
    if operation == 'add':
        Friend.make_friend(request.user, new_friend)
    elif operation == 'remove':
        Friend.lose_friend(request.user, new_friend)
    return redirect('home:home')

home/templates/home/home.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <div class="row">
      <div class="col-md-6">
        <h2>Home</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.post }}
            <br>
            <button type="submit">Submit</button>
        </form>
        <h2>{{ text }}</h2>
        {% for post in posts %}
            <h1>{{ post.post }}</h1>
            <p>Posted by {{ post.user.get_full_name }} on {{ post.created }}</p>
        {% endfor %}
    </div>

        <div class="col-md-6">
            <h2>Other People</h2>
            {% for user in users %}
            <div class="row">
            <div class="col-xs-6">
              <a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
                  <h3>{{ user.username }}</h3>
              </a>
            </div>

        {% if not user in friends %}
          <div class="col-md-4">
            <a href="{% url 'home:change_friends' operation='add' pk=user.pk %}">
            <button type="button" class="btn btn-success">Add Friend</button>
           </a>
            </div>
          {% endif %}
          </div>
        {% endfor %}

        <br>
        
        <h2>Friends</h2>
        {% for friend in friends %}

        <div class="row">
        <div class="col-xs-6">
            <a href="{% url 'accounts:view_profile_with_pk' pk=friend.pk %}"><h3>{{ friend.username }}</h3></a>
        </div>
        <div class="col-xs-6">
            <a href="{% url 'home:change_friends' operation='remove' pk=friend.pk %}">
            <button type="button" class="btn btn-default" style="margin-left: 20px;">Remove Friend</button>
          </a>
        </div>
      </div>


        {% endfor %}
    </div>
</div>
</div>
{% endblock %}