accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
      login,
      logout,
      password_reset,
      password_reset_done,
      password_reset_confirm,
      password_reset_complete
      )

urlpatterns = [

    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name="login"),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name="logout"),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit/$', views.edit_profile, name="edit_profile"),
    url(r'^change-password/$', views.change_password, name="change_password"),

    url(r'^reset-password/$', password_reset, {
    'template_name': 'accounts/reset_password.html',
    'post_reset_redirect': 'accounts:password_reset_done',
    'email_template_name': 'accounts/reset_password_email.html'},
    name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'},
    name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
    {'template_name': 'accounts/reset_password_confirm.html',
    'post_reset_redirect': 'accounts:password_reset_complete'},
    name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,
    {'template_name': 'accounts/reset_password_complete.html'},
     name='password_reset_complete'),

]

home/urls.py
from django.conf.urls import url
from home.views import HomeView
from . import views

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^connect/(?P<operation>.+)(?P<pk>\d+)/$', views.change_friends, name='change_friends')
]

maxdjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from maxdjango import views
from maxdjango.views import login_redirect
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.login_redirect, name="login_redirect"),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db import models

# Create your models here.
class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().filter(city='Addis Ababa')

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)

    AddisAbaba = UserProfileManager()

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegisterationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            ##'phone',
            'password1',
            'password2'
            )

    def save(self, commit=True):
        user = super(RegisterationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']


        if commit:
            user.save()

        return user

## we are using EditProfile instead of built in UserCreationForm, UserChangeForm
class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')
        ## exclude() to remove unwanted

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect
from accounts.forms import (
             RegisterationForm,
             EditProfileForm,
        )
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required  ## to give denial access if not authenticated/logged in


def register(request):
    if request.method == 'POST':
        form = RegisterationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/account')
    else:
        form = RegisterationForm()

        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)

## we use this decorators like this

## The pk parameter will be none if there is none but will be added if there is to differenciate view_profile and view_profile_with_pk
def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)

    else:
        user = request.user
    args = {'user': user}

    return render(request, 'accounts/profile.html', args)

##@login_required Started using instead middleware's
def edit_profile(request):
    if request.method == 'POST':
        ## form = UserChangeForm(request.POST, instance=request.user)  // but use instead my own EditProfileForm
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/account/profile')

    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        ## form = UserChangeForm(request.POST, instance=request.user)  // but use instead my own EditProfileForm
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/account/profile')

        else:
            return redirect('/account/change-password')

    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
<html>
  <head>
    <title>Profile</title>
    {% block head %}
    <title>Profile</title>
    {% endblock %}

  </head>
  <body>
    {% block body %}
    <div class="container">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">submit</button>
    </form>

    </div>
    {% endblock%}

  </body>
</html>

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
<html>
  <head>
    <title>Profile</title>
    {% block head %}
    <title>Profile</title>
    {% endblock %}

  </head>
  <body>
    {% block body %}
    <div class="container">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">submit</button>
    </form>

    </div>
    {% endblock%}

  </body>
</html>

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<h1>Welcome</h1>
<p>
  You can login here!
</p>
<h2>Login</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>
</div>
{%  endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<h1>Logged Out</h1>
<p>
    You have logged out!
</p>


{%  endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
<html>
  <head>
    <title>Profile</title>
    {% block head %}
    <title>Profile</title>
    {% endblock %}

  </head>
  <body>
    {% block body %}
    <div class="container">
        <p>Username: {{ user }}</p>
        <p>FirstName: {{ user.first_name }}</p>
        <p>LastName: {{ user.last_name }}</p>
        <p>EmailAddress: {{ user.email }}</p>
        <p>Description: {{  user.userprofile.description }}</p>
        <p>Phone: {{  user.userprofile.phone }}</p>
        <p>City: {{  user.userprofile.city }}</p>
        <p>Website: <a href="{{  user.userprofile.website }}" style="color:black">{{  user.userprofile.website }}</a></p>
        {% if user.userprofile.image %}
        <img src="{{ user.userprofile.image.url }}" width="240">
        {% endif %}
    </div>
    {% endblock%}

  </body>
</html>

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
  <h1>Register</h1>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}

  <button type="submit" class="btn btn-success">Submit</button>

</form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<h1>Password Reset</h1>
<p>
Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
</p>
<h6>Enter your Email Address below:</h6>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-success" type="submit">Reset Password</button>
</form>
</div>
{%  endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<h1>Password Reset Complete</h1>
<p>
  You have successfully resetted your password! Thanks!
</p>

<a href="{% url 'accounts:login' %}" style="color:black">Login</a>
</div>
{%  endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<h1>Enter your password</h1>
<p>
  Enter the password you want to change
</p>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-success" type="submit">Reset Password</button>
</form>
</div>
{%  endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<h1>Password Reset Sent!</h1>
<p>
  We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

  If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
</p>


</div>
{%  endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}