accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
      login,
      logout,
      password_reset,
      password_reset_done,
      password_reset_confirm,
      password_reset_complete
      )

urlpatterns = [

    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name="login"),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name="logout"),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit/$', views.edit_profile, name="edit_profile"),
    url(r'^change-password/$', views.change_password, name="change_password"),

    url(r'^reset-password/$', password_reset, {
    'template_name': 'accounts/reset_password.html',
    'post_reset_redirect': 'accounts:password_reset_done',
    'email_template_name': 'accounts/reset_password_email.html'},
    name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'},
    name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
    {'template_name': 'accounts/reset_password_confirm.html',
    'post_reset_redirect': 'accounts:password_reset_complete'},
    name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,
    {'template_name': 'accounts/reset_password_complete.html'},
     name='password_reset_complete'),

]

home/urls.py
from django.conf.urls import url
from home.views import HomeView
from . import views

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^connect/(?P<operation>.+)(?P<pk>\d+)/$', views.change_friends, name='change_friends')
]

maxdjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from maxdjango import views
from maxdjango.views import login_redirect
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.login_redirect, name="login_redirect"),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db import models

# Create your models here.
class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().filter(city='Addis Ababa')

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True)

    AddisAbaba = UserProfileManager()

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegisterationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            ##'phone',
            'password1',
            'password2'
            )

    def save(self, commit=True):
        user = super(RegisterationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']


        if commit:
            user.save()

        return user

## we are using EditProfile instead of built in UserCreationForm, UserChangeForm
class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')
        ## exclude() to remove unwanted

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect
from accounts.forms import (
             RegisterationForm,
             EditProfileForm,
        )
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required  ## to give denial access if not authenticated/logged in


def register(request):
    if request.method == 'POST':
        form = RegisterationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/account')
    else:
        form = RegisterationForm()

        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)

## we use this decorators like this

## The pk parameter will be none if there is none but will be added if there is to differenciate view_profile and view_profile_with_pk
def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)

    else:
        user = request.user
    args = {'user': user}

    return render(request, 'accounts/profile.html', args)

##@login_required Started using instead middleware's
def edit_profile(request):
    if request.method == 'POST':
        ## form = UserChangeForm(request.POST, instance=request.user)  // but use instead my own EditProfileForm
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/account/profile')

    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        ## form = UserChangeForm(request.POST, instance=request.user)  // but use instead my own EditProfileForm
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/account/profile')

        else:
            return redirect('/account/change-password')

    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

accounts/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
    integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
    crossorigin="anonymous">


    {% load static %}

    <link rel="stylesheet" href="{% static 'accounts/style.css' %}" type="text/css"

    <script type="text/javascript" href="{% static 'accounts/js/bootstrap.min.js' %}" </script>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
     {% block head %}
     <title>Base</title>
     {% endblock %}

  </head>
  <body>


<div class="container">
    <nav class="navbar navbar-expand-lg navbar-inverse bg-dark">
  <a class="navbar-brand" href="#">   BisratYalew   </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% if user.is_authenticated %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home:home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:view_profile' %}">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:edit_profile' %}">Edit-Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:change_password' %}">Change-Password</a>
      </li>
    </ul>

    <ul class="navbar-nav navbar-right">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
      </li>
    </ul>


    {% else %}
    <ul class="navbar-nav mr-auto">
           <!-- we can add a left side nav items here  -->
      </ul>

      <ul class="nav navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:reset_password' %}">Reset-Password</a>
        </li>
      </ul>

      <ul class="navbar-nav navbar-right">
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
        <li class="active"><a class="nav-link" href="{% url 'accounts:register' %}">Register</a></li>
      </ul>
     {% endif %}

   </div>
</nav>
</div>
      {% block body %}
    {% endblock%}
  </body>

  <script src="https://code.jquery.com/jquery-3.2.1.min.js"
       integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
       crossorigin="anonymous"></script>

   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
    integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
    crossorigin="anonymous">
    </script>


</html>